# Generated by Django 4.0.7 on 2022-09-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_act'),
    ]

    operations = [
        migrations.DeleteModel(
            name='act',
        ),
    ]
